#ifndef DEFINE_H_INCLUDED
#define DEFINE_H_INCLUDED

#define	CONSTSY	0//定义词法分析的各个单词类型
#define	INTSY	1
#define	CHARSY	2
#define	VOIDSY	3
#define MAINSY 4
#define	IFSY	5
#define	WHILESY	6
#define	SWITCHSY	7
#define	CASESY	8
#define	DEFAULTSY	9
#define	SCANFSY	10
#define	PRINTFSY	11
#define	RETURNSY	12
#define EOFSY 13

#define CharSY 27
#define NoteSY 28
#define StringSY 29
#define	IdSY	30
#define	IntSY	31
#define	COMMASY	32
#define	EQUSY	33
#define	SEMISY	34
#define	ASSIGNSY	35
#define	PLUSSY	36
#define	MINUSSY	37
#define	STARSY	38
#define	DIVSY	39
#define	UNEQUSY	40
#define	LITTLESY	41
#define	LITTLEEQUSY	42
#define	GREATERSY	43
#define	GREATEREQUSY	44
#define	LPARSY	45
#define	RPARSY	46
#define LBRACK  47
#define RBRACK 48
#define LBRACE 49
#define RBRACE 50
#define COLON 51

#define ERROR 404
#define NOTYPE 405
#define Const 406
#define Variable 407
#define Withrefunc 408
#define Norefunc 409
#define Array 410
#define Para 411
#define TVAR 412
#define success 666
#define MAX 300//定义其他宏

#define Resvnum 52

#define tmax 1000
#define bmax 1000
#define amax 1000
#define smax 1000
#define dmax 1000

#define VAR 0
#define Funcdec 1
#define SET 2
#define JUMP 3
#define RET 4
#define ADD 5
#define SUB 6
#define MULT 7
#define DIV 8
#define Arrayasg 9
#define Arrayout 10
#define Callret 11
#define Call 12
#define Npara 13
#define LITEQU 14
#define LIT 15
#define GRTEQU 16
#define GRT 17
#define EQUU 18
#define UNEQU 19
#define BNZ 20
#define BNE 21
#define SCANF 22
#define PRINTF 23
#define ASSIGN 24
#define PULL 25

#define INT "int"
#define CHAR "char"
#define VOID "void"
#define STRING "string"
#define MAIN "main"
#define NULLL "-"
#define ZERO "0"
#define ONE "1"
#endif // DEFINE_H_INCLUDED
